### ISSUE TITLE
texte sponsor disparait au hover

### ISSUE THREAD

**Issue by cbalit** [bow-paris/bow-paris.github.io#20]

**Comment by nicoespeon** [comment]
@cbalit >  c'est un TODO ou un bug en fait ? On dirait une description de bug mais je n'arrive pas à le reproduire (pas de texte qui disparait au survol chez moi) =)

**Comment by cbalit** [comment]
Pour moi c'est un bug. Je recheck

**Comment by cbalit** [comment]
effectivement je l'ai plus. Je close
