### ISSUE TITLE
Size Logo sponsors

### ISSUE THREAD

**Issue by cbalit** [bow-paris/bow-paris.github.io#26]
Il faut fixer les images des logo en fonction des sections:
Par ex:
- Gold 200px
- Silver 150px
- Bronze 100px
- Basic 75px

**Comment by DjebbZ** [comment]
Pour info, on a commencé à bosser dessus.

**Comment by cbalit** [comment]
Je trouve que la taille des logos est un peu petite. Vous en pensez quoi ? Ca sera peut être mieux quand il y en aura plus.

**Comment by nicoespeon** [comment]
Peut être grossir un peu les golds. Mais sinon ça rendra mieux quand il y en aura plus.

Par contre, je retirerai bien le "titre" en dessous des logos. D'habitude y'a juste le logo pour les sponsors (qui est un lien, mais y'a pas de label en dessous).

**Comment by DjebbZ** [comment]
Pas faux pour retirer les titres dessous.

Khalid aka DjebbZ
@Dj3bbZ

2015-03-05 11:57 GMT+01:00 Nicolas Carlo notifications@github.com:

**Comment by nicoespeon** [comment]
Du coup on peut considérer que c'est closed avec #35
